# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Requests
    App\Http\Request\:
        resource: '../src/Http/Request'
 
    App\Contract\Service\BattleSimulatorInterface:
        class: App\Service\BattleSimulator

    App\Contract\Service\DiceRollerInterface:
        class: App\Service\DiceRoller

    App\Contract\Service\ArmyStatsCalculatorInterface:
        class: App\Service\ArmyStatsCalculator

    App\Contract\Service\BattleLoggerInterface:
        class: App\Service\BattleLogger

    App\Contract\Service\ArmyServiceInterface:
        class: App\Service\ArmyService

    #
    # FACTORIES
    #
    App\Contract\Service\ArmyFactoryInterface:
        class: App\Service\Factory\ArmyFactory

    App\Contract\Service\BattleFactoryInterface:
        class: App\Service\Factory\BattleFactory

    App\Contract\Service\ModifierFactoryInterface:
        class: App\Service\Factory\ModifierFactory

    App\Contract\Service\RegimentFactoryInterface:
        class: App\Service\Factory\RegimentFactory

